CicekciBaciDapper/Models/CicekBilgiModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CicekciBaciDapper.Models
{
    public class CicekBilgiModel
    {
        public int cicekNo { get; set; }
        public string cicekadi { get; set;}
        public string renk { get; set;}
        public decimal fiyat { get; set;}
        public int adet { get; set;}
        public string mensei { get; set;}
    }
}

CicekciBaciDapper/Models/DP.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.SqlClient;
using System.Data;
using Dapper;

namespace CicekciBaciDapper.Models
{
    public static class DP
    {
        private static string connectionString = "Server = LAPTOP-DI6H08K1; Database = CicekciBaci; Integrated Security= true;";

        public static void ExReturn(string procadi, DynamicParameters param= null)
        {
            using (SqlConnection baglan =  new SqlConnection(connectionString))
            {
                baglan.Open();
                baglan.Execute(procadi, param, commandType:CommandType.StoredProcedure);
            }
        }
        public static IEnumerable<T> ReturnList<T>(string procadi, DynamicParameters param = null)
        {
            using (SqlConnection baglan = new SqlConnection(connectionString))
            {
                baglan.Open();
                return baglan.Query<T>(procadi, param, commandType: CommandType.StoredProcedure);

            }
        }
    }
}

CicekciBaciDapper/Models/MusterilerModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CicekciBaciDapper.Models
{
    public class MusterilerModel
    {
        public int MusteriNo { get; set; }
        public string MusteriAdi { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }

    }
}

CicekciBaciDapper/Models/TedarikcilerModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CicekciBaciDapper.Models
{
    public class TedarikcilerModel
    {
        public int TedarikciNo { get; set; }
        public string TedarikciAdi { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
    }
}

CicekciBaciDapper/Controllers/CicekBilgiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using CicekciBaciDapper.Models;

namespace CicekciBaciDapper.Controllers
{
    public class CicekBilgiController : Controller
    {
        // GET: CicekBilgi
        public ActionResult Index()
        {
            return View(DP.ReturnList<CicekBilgiModel>("CicekListele"));
        }

        public ActionResult EY(int id = 0)
        {
            if (id == 0)
            {
                return View();
            }
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@cicekNo", id);
                return View(DP.ReturnList<CicekBilgiModel>("CicekSirala", param).FirstOrDefault<CicekBilgiModel>());

            }
        }

        [HttpPost]
        public ActionResult EY(CicekBilgiModel cicekBilgi)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@cicekNo", cicekBilgi.cicekNo);
            param.Add("@cicekAdi", cicekBilgi.cicekadi);
            param.Add("@renk", cicekBilgi.renk);
            param.Add("@fiyat", cicekBilgi.fiyat);
            param.Add("@adet", cicekBilgi.adet);
            param.Add("@mensei", cicekBilgi.mensei);
            DP.ExReturn("CicekEY", param);
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int id=0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("cicekNo", id);
            DP.ExReturn("CicekSil", param);
            return RedirectToAction("Index");
        }
    }
}

CicekciBaciDapper/Controllers/MusterilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using CicekciBaciDapper.Models;

namespace CicekciBaciDapper.Controllers
{
    public class MusterilerController : Controller
    {
        // GET: Musteriler
        public ActionResult Index()
        {
            return View(DP.ReturnList<MusterilerModel>("MusteriListele"));
        }

        public ActionResult EY(int id =0)
        {
            if (id ==0)
            {
                return View();
            }
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@MusteriNo", id);
                return View(DP.ReturnList<MusterilerModel>("MusteriSirala", param).FirstOrDefault<MusterilerModel>());
            }
        }

        [HttpPost]
        public ActionResult EY(MusterilerModel musteri)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@MusteriNo", musteri.MusteriNo);
            param.Add("@MusteriAdi", musteri.MusteriAdi);
            param.Add("@telefon", musteri.telefon);
            param.Add("@email", musteri.email);
            DP.ExReturn("MusteriEY",param);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id=0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@MusteriNo", id);
            DP.ExReturn("MusteriSil", param);
            return RedirectToAction("Index");
        }
    }
}

CicekciBaciDapper/Controllers/TedarikciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using CicekciBaciDapper.Models;

namespace CicekciBaciDapper.Controllers
{
    public class TedarikciController : Controller
    {
        // GET: Tedarikci
        public ActionResult Index()
        {
            return View(DP.ReturnList<TedarikcilerModel>("TedarikciListele"));
        }

        public ActionResult EY(int id=0)
        {
            if (id==0)
            {
                return View();

            }
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@TedarikciNo", id);
                return View(DP.ReturnList<TedarikcilerModel>("TedarikciSirala", param).FirstOrDefault<TedarikcilerModel>());
            }
        }

        [HttpPost]
        public ActionResult EY(TedarikcilerModel tedarikci)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@TedarikciNo", tedarikci.TedarikciNo);
            param.Add("@TedarikciAdi", tedarikci.TedarikciAdi);
            param.Add("@Ulke", tedarikci.Ulke);
            param.Add("@Sehir", tedarikci.Sehir);
            DP.ExReturn("TedarikciEY", param);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id =0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@TedariikciNo", id);
            DP.ExReturn("TedarikciSil", param);
            return RedirectToAction("Index");   
        }
    }
}

CicekciBaciDapper/Views/CicekBilgi/EY.cshtml
@model CicekciBaciDapper.Models.CicekBilgiModel

@{
    ViewBag.Title = "EY";
}

<h2>Çiçek Bilgi</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(Model=> Model.cicekNo)
    
    <div class="form-horizontal">
        <h4>CicekBilgiModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.cicekadi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cicekadi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cicekadi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.renk, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.renk, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.renk, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fiyat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fiyat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mensei, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mensei, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mensei, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CicekciBaciDapper/Views/CicekBilgi/Index.cshtml
@model IEnumerable<CicekciBaciDapper.Models.CicekBilgiModel>

@{
    ViewBag.Title = "Index";
}

<h2>Çiçek Bilgi</h2>

<p>
    @Html.ActionLink("Yeni", "EY", new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.cicekadi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.renk)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fiyat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.adet)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.mensei)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.cicekadi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.renk)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fiyat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.adet)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.mensei)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "EY", new { id=item.cicekNo }, new { @class = "btn btn-warning" }) |
            
            @Html.ActionLink("sil", "Delete", new { id = item.cicekNo }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

CicekciBaciDapper/Views/Musteriler/EY.cshtml
@model CicekciBaciDapper.Models.MusterilerModel

@{
    ViewBag.Title = "EY";
}

<h2>Müşteriler</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(Model=> Model.MusteriNo)
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MusteriAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MusteriAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MusteriAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CicekciBaciDapper/Views/Musteriler/Index.cshtml
@model IEnumerable<CicekciBaciDapper.Models.MusterilerModel>

@{
    ViewBag.Title = "Index";
}

<h2>Müşteriler</h2>

<p>
    @Html.ActionLink("Ekle", "EY", new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MusteriAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telefon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MusteriAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.telefon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "EY", new {  id=item.MusteriNo }, new { @class = "btn btn-warning" }) |
            
            @Html.ActionLink("Sil", "Delete", new { id = item.MusteriNo }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

CicekciBaciDapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Çiçekci Bacı", "Index", "CicekBilgi", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Çiçekler", "Index", "CicekBilgi")</li>
                    <li>@Html.ActionLink("Müşteriler", "Index", "Musteriler")</li>
                    <li>@Html.ActionLink("Tedarikçiler", "Index", "Tedarikci")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CicekciBaciDapper/Views/Tedarikci/EY.cshtml
@model CicekciBaciDapper.Models.TedarikcilerModel

@{
    ViewBag.Title = "EY";
}

<h2>Tedarikçiler</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(Model => Model.TedarikciNo)
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TedarikciAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TedarikciAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TedarikciAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ulke, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ulke, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ulke, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sehir, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sehir, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sehir, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index", new {@class="btn btn-info"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CicekciBaciDapper/Views/Tedarikci/Index.cshtml
@model IEnumerable<CicekciBaciDapper.Models.TedarikcilerModel>

@{
    ViewBag.Title = "Index";
}

<h2>Tedarikçiler</h2>

<p>
    @Html.ActionLink("Yeni", "EY", new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TedarikciAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ulke)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sehir)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TedarikciAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ulke)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sehir)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "EY", new { id=item.TedarikciNo }, new { @class = "btn btn-warning" }) |
            
            @Html.ActionLink("Sil", "Delete", new { id = item.TedarikciNo }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>